const seed={categories:['교육 기획','홍보','프로그램 운영','회계','자원봉사 관리','IT / 시스템'],tasks:[
{id:1,title:'리더십 워크숍 자료 준비',assignee:'김철수',category:'교육 기획',priority:'높음',due:'2026-08-08',status:'진행 중',progress:70},
{id:2,title:'후원자 대상 뉴스레터 발송',assignee:'이영희',category:'홍보',priority:'보통',due:'2026-08-10',status:'진행 중',progress:40},
{id:3,title:'아동 프로그램 만족도 조사',assignee:'박민수',category:'프로그램 운영',priority:'높음',due:'2026-08-07',status:'검토/대기',progress:80},
{id:4,title:'회계 보고서 작성',assignee:'최지은',category:'회계',priority:'보통',due:'2026-08-12',status:'진행 중',progress:30},
{id:5,title:'신규 자원봉사자 교육 계획',assignee:'김서연',category:'자원봉사 관리',priority:'보통',due:'2026-08-15',status:'검토/대기',progress:50},
{id:6,title:'홈페이지 FAQ 업데이트',assignee:'정우진',category:'IT / 시스템',priority:'낮음',due:'2026-08-05',status:'완료',progress:100}],
meetings:[
{id:1,week:'2026-W32',date:'2026-08-04',title:'주간 회의',author:'김철수',attendees:['김철수','이영희','박민수','최지은','김서연'],topics:['리더십 워크숍 자료 준비 현황 공유','후원자 대상 뉴스레터 발송 계획 논의','아동 프로그램 만족도 조사 진행 상황 점검','회계 보고서 작성 일정 조정'],decisions:['워크숍 발표자료 초안 1차 검토','뉴스레터 8월호 발송','만족도 조사 최종 취합'],next:['발표자료 최종본 확정','뉴스레터 반응 분석','만족도 조사 결과 분석']},
{id:2,week:'2026-W31',date:'2026-07-28',title:'주간 회의',author:'이영희',attendees:['이영희','김철수','박민수'],topics:['프로젝트 진행 상황 공유'],decisions:['일정 재조정'],next:['후속 점검']}],
events:[{id:1,title:'팀 회의',date:'2026-08-05',type:'회의'},{id:2,title:'후원자 미팅',date:'2026-08-05',type:'내부 일정'},{id:3,title:'만족도 조사 인터뷰',date:'2026-08-06',type:'내부 일정'},{id:4,title:'리더십 워크숍',date:'2026-08-07',type:'내부 일정'},{id:5,title:'자원봉사자 교육',date:'2026-08-08',type:'내부 일정'}],members:[{name:'김철수',role:'관리자'},{name:'이영희',role:'팀원'},{name:'박민수',role:'팀원'},{name:'최지은',role:'팀원'},{name:'김서연',role:'팀원'},{name:'정우진',role:'팀원'}]};
let data=JSON.parse(localStorage.getItem('teamDashboardData')||'null')||seed;let currentMeeting=data.meetings[0]?.id;let calDate=new Date(2026,7,1);
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem('teamDashboardData',JSON.stringify(data));renderAll()}
function badge(status){const cls=status==='완료'?'blue':status==='진행 중'?'green':status==='검토/대기'?'orange':'red';return `<span class="badge ${cls}">${status}</span>`}
function renderNav(){ $$('.nav-item').forEach(b=>b.onclick=()=>showView(b.dataset.view)); $$('[data-view-link]').forEach(b=>b.onclick=()=>showView(b.dataset.viewLink));}
function showView(id){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+id).classList.add('active');$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===id));const t={dashboard:['대시보드','팀원들의 업무 현황을 한눈에 확인하세요.'],tasks:['업무 관리','업무를 등록하고 이력을 관리합니다.'],meetings:['주간 회의록','회의 내용과 결정사항을 공유합니다.'],calendar:['통합 캘린더','업무 일정과 Google Calendar 연동을 준비합니다.'],admin:['관리자 페이지','업무 분류와 시스템 설정을 관리합니다.']}[id];$('#pageTitle').textContent=t[0];$('#pageSubtitle').textContent=t[1];}
function renderCategories(){['#dashboardCategoryFilter','#taskCategoryFilter'].forEach(sel=>{const cur=$(sel)?.value;$(sel).innerHTML='<option value="all">전체 카테고리</option>'+data.categories.map(c=>`<option>${c}</option>`).join('');if(cur)$(sel).value=cur});$('#taskCategory').innerHTML=data.categories.map(c=>`<option>${c}</option>`).join('');$('#categoryList').innerHTML=data.categories.map(c=>`<div class="category-row"><span>${c}</span><button onclick="removeCategory('${c}')">삭제</button></div>`).join('')}
function filteredTasks(prefix){const q=$(`#${prefix}Search`)?.value?.toLowerCase()||'';const cat=$(`#${prefix}CategoryFilter`)?.value||'all';const st=$(`#${prefix}StatusFilter`)?.value||'all';return data.tasks.filter(t=>(!q||`${t.title} ${t.assignee}`.toLowerCase().includes(q))&&(cat==='all'||t.category===cat)&&(st==='all'||t.status===st))}
function taskRows(tasks,full=true){return tasks.map(t=>`<tr><td><strong>${t.title}</strong></td><td>${t.assignee}</td><td>${t.category}</td>${full?`<td>${t.priority}</td>`:''}<td>${t.due}</td><td>${badge(t.status)}</td><td><div class="progress"><span style="width:${t.progress}%"></span></div> ${t.progress}%</td>${full?'':`<td class="small-actions"><button onclick="deleteTask(${t.id})">삭제</button></td>`}</tr>`).join('')}
function renderDashboard(){const total=data.tasks.length,counts=s=>data.tasks.filter(t=>t.status===s).length;const stats=[['📋','전체 업무',total],['✅','진행 중',counts('진행 중')],['⏳','검토/대기',counts('검토/대기')],['🎯','완료',counts('완료')],['📅','이번 주 마감',data.tasks.filter(t=>t.due>='2026-08-04'&&t.due<='2026-08-10').length]];$('#statsGrid').innerHTML=stats.map(s=>`<div class="stat-card"><div class="stat-icon">${s[0]}</div><div><span>${s[1]}</span><strong>${s[2]}건</strong></div></div>`).join('');$('#dashboardTaskRows').innerHTML=taskRows(filteredTasks('dashboard'));$('#donutTotal').textContent=total;const colors={'진행 중':'#15a96b','검토/대기':'#f59e0b','완료':'#7c5ce5','지연':'#ef4444'};$('#statusLegend').innerHTML=Object.keys(colors).map(s=>`<div class="legend-row"><span><i class="legend-dot" style="background:${colors[s]}"></i>${s}</span><strong>${counts(s)}건</strong></div>`).join('');$('#miniCalendar').innerHTML=['8/4','8/5','8/6','8/7','8/8'].map(d=>{const iso='2026-08-'+d.split('/')[1].padStart(2,'0');return `<div class="day-card"><strong>${d}</strong>${data.events.filter(e=>e.date===iso).map(e=>`<div class="event-pill">${e.title}</div>`).join('')}</div>`}).join('');$('#recentMeetings').innerHTML=data.meetings.slice(0,4).map(m=>`<div class="list-item"><div><strong>${m.date} 주간 회의</strong><p>${m.author}</p></div><span>›</span></div>`).join('');$('#memberWork').innerHTML=data.tasks.slice(0,6).map(t=>`<div class="list-item"><div><strong>${t.assignee}</strong><p>${t.title}</p></div>${badge(t.status)}</div>`).join('')}
function renderTasks(){$('#taskRows').innerHTML=taskRows(filteredTasks('task'),false)}
function renderMeetings(){const selected=data.meetings.find(m=>m.id===currentMeeting)||data.meetings[0];$('#meetingList').innerHTML=data.meetings.map(m=>`<div class="meeting-card ${m.id===selected.id?'active':''}" onclick="selectMeeting(${m.id})"><strong>${m.week} (${m.date})</strong><h3>${m.title}</h3><p>${m.author} · 작성 완료</p></div>`).join('');$('#meetingDetail').innerHTML=`<div class="panel-head"><div><span class="badge blue">${selected.week}</span><h2 style="margin-top:10px">${selected.title}</h2><p>${selected.date} · 작성자 ${selected.author}</p></div><button class="secondary">수정</button></div><div><strong>참석자</strong><p>${selected.attendees.join(', ')}</p></div><div class="meeting-detail-block"><h3>1. 주요 논의 내용</h3><ul>${selected.topics.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="meeting-detail-block"><h3>2. 결정 사항</h3><ul>${selected.decisions.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="meeting-detail-block"><h3>3. 다음 주 계획</h3><ul>${selected.next.map(x=>`<li>${x}</li>`).join('')}</ul></div>`;$('#meetingSide').innerHTML=`<h2>회의록 이력</h2><div class="timeline" style="margin-top:16px"><div class="timeline-item"><strong>${selected.date} 18:20</strong><p>${selected.author} · 회의록 초안 작성</p></div><div class="timeline-item"><strong>${selected.date} 17:55</strong><p>결정사항 내용 수정</p></div><div class="timeline-item"><strong>${selected.date} 17:30</strong><p>담당자 및 기한 수정</p></div></div><div class="meeting-detail-block"><h3>연관 업무</h3>${data.tasks.slice(0,5).map(t=>`<div class="list-item"><div><strong>${t.title}</strong><p>${t.assignee}</p></div>${badge(t.status)}</div>`).join('')}</div>`}
function renderCalendar(){const y=calDate.getFullYear(),m=calDate.getMonth();$('#calendarTitle').textContent=`${y}년 ${m+1}월`;const first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();let html='';for(let i=0;i<first;i++)html+='<div></div>';for(let d=1;d<=days;d++){const iso=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;html+=`<div><span class="date-num">${d}</span>${data.events.filter(e=>e.date===iso).map(e=>`<span class="calendar-event">${e.title}</span>`).join('')}</div>`}$('#calendarGrid').innerHTML=html}
function renderAdmin(){$('#memberList').innerHTML=data.members.map(m=>`<div class="member-row"><div><strong>${m.name}</strong><p>${m.role}</p></div><span class="badge ${m.role==='관리자'?'blue':'green'}">${m.role}</span></div>`).join('')}
function renderAll(){renderCategories();renderDashboard();renderTasks();renderMeetings();renderCalendar();renderAdmin()}
window.selectMeeting=id=>{currentMeeting=id;renderMeetings()};window.deleteTask=id=>{data.tasks=data.tasks.filter(t=>t.id!==id);save()};window.removeCategory=c=>{if(data.tasks.some(t=>t.category===c))return alert('사용 중인 카테고리는 삭제할 수 없습니다.');data.categories=data.categories.filter(x=>x!==c);save()}
$$('[data-open-task]').forEach(b=>b.onclick=()=>$('#taskDialog').showModal());$('#newEventBtn').onclick=()=>$('#eventDialog').showModal();$('#prevMonth').onclick=()=>{calDate=new Date(calDate.getFullYear(),calDate.getMonth()-1,1);renderCalendar()};$('#nextMonth').onclick=()=>{calDate=new Date(calDate.getFullYear(),calDate.getMonth()+1,1);renderCalendar()};
$('#saveTaskBtn').onclick=e=>{e.preventDefault();if(!$('#taskTitle').value||!$('#taskAssignee').value||!$('#taskDue').value)return;data.tasks.unshift({id:Date.now(),title:$('#taskTitle').value,assignee:$('#taskAssignee').value,category:$('#taskCategory').value,status:$('#taskStatus').value,priority:$('#taskPriority').value,due:$('#taskDue').value,progress:Number($('#taskProgress').value||0)});$('#taskDialog').close();$('#taskForm').reset();save()};
$('#saveEventBtn').onclick=e=>{e.preventDefault();if(!$('#eventTitle').value||!$('#eventStart').value)return;data.events.push({id:Date.now(),title:$('#eventTitle').value,date:$('#eventStart').value,type:$('#eventType').value});$('#eventDialog').close();$('#eventForm').reset();save()};
$('#categoryForm').onsubmit=e=>{e.preventDefault();const v=$('#categoryName').value.trim();if(v&&!data.categories.includes(v)){data.categories.push(v);$('#categoryName').value='';save()}};
['dashboardSearch','dashboardCategoryFilter','dashboardStatusFilter'].forEach(id=>$('#'+id).addEventListener('input',renderDashboard));['taskSearch','taskCategoryFilter','taskStatusFilter'].forEach(id=>$('#'+id).addEventListener('input',renderTasks));
$('#newMeetingBtn').onclick=()=>alert('현재 버전은 화면 데모입니다. Supabase 연동 후 회의록 작성·저장 기능을 연결하세요.');
renderNav();renderAll();
